export const GET_SHOW_ACTION = 'GET_SHOW_ACTION';
export const GET_SEASONS_ACTION = 'GET_SEASONS_ACTION';
export const GET_EPISODES_BY_SEASON_ACTION = 'GET_EPISODES_BY_SEASON_ACTION';
export const GET_EPISODE_ACTION = 'GET_EPISODE_ACTION';